name: Classify Files
on:
  push:
    branches:
      - main
jobs:
  classify_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Process PDF files (root level only)
        run: |
          set -euo pipefail
          mkdir -p sheets
          # Sử dụng find với -print0 để xử lý file an toàn hơn
          find . -maxdepth 1 -type f -name '*.pdf' -print0 | while IFS= read -r -d $'\0' f; do
            fileName=$(basename "$f")
            dest="sheets/$fileName"
            if [ -e "$dest" ]; then
              # So sánh nội dung file nếu tên trùng
              if cmp -s "$f" "$dest"; then
                echo "::warning:: Duplicate PDF '$fileName' đã tồn tại, bỏ qua upload."
                rm "$f"
              else
                base="${fileName%.*}"
                ext="${fileName##*.}"
                version=1
                newDest="sheets/${base}@v_$(printf "%02d" $version).${ext}"
                while [ -e "$newDest" ]; do
                  version=$((version+1))
                  newDest="sheets/${base}@v_$(printf "%02d" $version).${ext}"
                done
                echo "::warning:: File PDF '$fileName' có nội dung khác nhau; lưu dưới dạng phiên bản: $(basename "$newDest")"
                mv "$f" "$newDest"
              fi
            else
              mv "$f" "$dest"
            fi
          done

      - name: Process MSCZ files (root level only)
        run: |
          set -euo pipefail
          mkdir -p scores
          find . -maxdepth 1 -type f -name '*.mscz' -print0 | while IFS= read -r -d $'\0' f; do
            fileName=$(basename "$f")
            dest="scores/$fileName"
            if [ -e "$dest" ]; then
              if cmp -s "$f" "$dest"; then
                echo "::warning:: Duplicate MSCZ '$fileName' đã tồn tại, bỏ qua upload."
                rm "$f"
              else
                base="${fileName%.*}"
                ext="${fileName##*.}"
                version=1
                newDest="scores/${base}@v_$(printf "%02d" $version).${ext}"
                while [ -e "$newDest" ]; do
                  version=$((version+1))
                  newDest="scores/${base}@v_$(printf "%02d" $version).${ext}"
                done
                echo "::warning:: File MSCZ '$fileName' có nội dung khác nhau; lưu dưới dạng phiên bản: $(basename "$newDest")"
                mv "$f" "$newDest"
              fi
            else
              mv "$f" "$dest"
            fi
          done

      - name: Commit changes if any
        run: |
          set -euo pipefail
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff-index --quiet HEAD --; then
            echo "Không có thay đổi để commit"
          else
            git commit -m 'Classify files into sheet and score folders'
            git push
          fi
